Add fluent validation
victorDivino/Money-Admin pull request #14
Opened 2020-02-14 18:41 UTC by lucaslima10077

### Installation FluentValidation
- install and configuration

### Added validator
-Added class **CreateAccountCommandValidator**

### Added UnitTest
-Added class tests **CreateAccountCommandTests** to guarantee the quality

2020-02-14 18:42 UTC, lucaslima10077 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add FluentValidation](https://trello.com/c/ZyEwHtAj/6-add-fluentvalidation)

2020-02-14 19:12 UTC, victorDivino requested changes

2020-02-14 19:12 UTC, victorDivino commented on src/MoneyAdmin.Domain/Validators/CreateAccountCommandValidator.cs
> +            RuleFor(x => x.Name).NotNull().NotEmpty().WithMessage("is required");
The  message must be **The Name is required**

2020-02-14 19:12 UTC, victorDivino commented on src/MoneyAdmin.Domain/Validators/CreateAccountCommandValidator.cs
> +            RuleFor(x => x.InitialValue).GreaterThanOrEqualTo(0).WithMessage("should be lower or equals than 0");
Remove the rule for Initial Value because it may have debit balance.

2020-02-14 19:12 UTC, victorDivino commented on src/Tests/MoneyAdmin.Domain.UnitTests/Commands/CreateAccountCommandTests.cs
> +    public sealed class CreateAccountCommandTests
The class' name must be **CreateAccountCommandValidatorTests**

2020-02-14 19:12 UTC, victorDivino commented on src/Tests/MoneyAdmin.Domain.UnitTests/Commands/CreateAccountCommandTests.cs
> +        public void CreateAccountShouldValid()
The method's name must be **CreateAccountCommandValidatorShouldBeTrue**

2020-02-14 19:12 UTC, victorDivino commented on src/MoneyAdmin.Domain/Validators/CreateAccountCommandValidator.cs
> +            RuleFor(x => x.Name).NotNull().NotEmpty().WithMessage("is required");
Add rule for name max length

2020-02-14 19:12 UTC, victorDivino commented on src/Tests/MoneyAdmin.Domain.UnitTests/Commands/CreateAccountCommandTests.cs
> +        public void CreateAccountWithNameEmptyOrInitialValueLowerZeroShouldInvalid()
For each validation create a method please.

2020-02-14 19:14 UTC, victorDivino requested changes

2020-02-14 19:14 UTC, victorDivino commented on src/Tests/MoneyAdmin.Domain.UnitTests/Commands/CreateAccountCommandTests.cs
> +namespace MoneyAdmin.Domain.Commands
The namespace must be **MoneyAdmin.Domain.Validators**

2020-02-17 15:31 UTC, victorDivino approved these changes

2020-02-17 15:32 UTC, merged